# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rosa_freeze_ui/rfreeze.ui'
#
# Created: Fri Feb 27 04:16:54 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RFreeze(object):
    def setupUi(self, RFreeze):
        RFreeze.setObjectName("RFreeze")
        RFreeze.resize(620, 369)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RFreeze.sizePolicy().hasHeightForWidth())
        RFreeze.setSizePolicy(sizePolicy)
        RFreeze.setMinimumSize(QtCore.QSize(100, 0))
        RFreeze.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(RFreeze)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(RFreeze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 15))
        self.label_3.setBaseSize(QtCore.QSize(100, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_status = QtWidgets.QLabel(RFreeze)
        self.label_status.setObjectName("label_status")
        self.horizontalLayout_3.addWidget(self.label_status)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnEnable = QtWidgets.QPushButton(RFreeze)
        self.btnEnable.setObjectName("btnEnable")
        self.horizontalLayout_2.addWidget(self.btnEnable)
        self.btnMerge = QtWidgets.QPushButton(RFreeze)
        self.btnMerge.setObjectName("btnMerge")
        self.horizontalLayout_2.addWidget(self.btnMerge)
        self.btnExit = QtWidgets.QPushButton(RFreeze)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_2.addWidget(self.btnExit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(RFreeze)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(RFreeze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.comboStorage = QtWidgets.QComboBox(RFreeze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboStorage.sizePolicy().hasHeightForWidth())
        self.comboStorage.setSizePolicy(sizePolicy)
        self.comboStorage.setObjectName("comboStorage")
        self.comboStorage.addItem("")
        self.comboStorage.addItem("")
        self.comboStorage.addItem("")
        self.horizontalLayout_6.addWidget(self.comboStorage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelDevice = QtWidgets.QLabel(RFreeze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDevice.sizePolicy().hasHeightForWidth())
        self.labelDevice.setSizePolicy(sizePolicy)
        self.labelDevice.setMinimumSize(QtCore.QSize(0, 0))
        self.labelDevice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDevice.setObjectName("labelDevice")
        self.horizontalLayout_5.addWidget(self.labelDevice)
        self.lineDevName = QtWidgets.QLineEdit(RFreeze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineDevName.sizePolicy().hasHeightForWidth())
        self.lineDevName.setSizePolicy(sizePolicy)
        self.lineDevName.setObjectName("lineDevName")
        self.horizontalLayout_5.addWidget(self.lineDevName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(RFreeze)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.folderList = QtWidgets.QListWidget(RFreeze)
        self.folderList.setObjectName("folderList")
        self.horizontalLayout_4.addWidget(self.folderList)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnAddFolder = QtWidgets.QCommandLinkButton(RFreeze)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/green-plus-th.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddFolder.setIcon(icon)
        self.btnAddFolder.setObjectName("btnAddFolder")
        self.verticalLayout_3.addWidget(self.btnAddFolder)
        self.btnRmFolder = QtWidgets.QCommandLinkButton(RFreeze)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/red-minus-th.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRmFolder.setIcon(icon1)
        self.btnRmFolder.setObjectName("btnRmFolder")
        self.verticalLayout_3.addWidget(self.btnRmFolder)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.busyBar = QtWidgets.QProgressBar(RFreeze)
        self.busyBar.setMaximum(103)
        self.busyBar.setProperty("value", 24)
        self.busyBar.setObjectName("busyBar")
        self.gridLayout_2.addWidget(self.busyBar, 0, 0, 1, 1)
        self.busyLabel = QtWidgets.QLabel(RFreeze)
        self.busyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.busyLabel.setObjectName("busyLabel")
        self.gridLayout_2.addWidget(self.busyLabel, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(RFreeze)
        QtCore.QMetaObject.connectSlotsByName(RFreeze)

    def retranslateUi(self, RFreeze):
        _translate = QtCore.QCoreApplication.translate
        RFreeze.setWindowTitle(_translate("RFreeze", "ROSA Freeze"))
        self.label_3.setText(_translate("RFreeze", "ROSA Freeze Status:"))
        self.label_status.setText(_translate("RFreeze", "Enabled"))
        self.btnEnable.setText(_translate("RFreeze", "Enable"))
        self.btnMerge.setText(_translate("RFreeze", "Save current state"))
        self.btnExit.setText(_translate("RFreeze", "Exit"))
        self.label_2.setText(_translate("RFreeze", "Freeze Settings"))
        self.label.setText(_translate("RFreeze", "Storage type to store new file versions:"))
        self.comboStorage.setItemText(0, _translate("RFreeze", "tmpfs"))
        self.comboStorage.setItemText(1, _translate("RFreeze", "device"))
        self.comboStorage.setItemText(2, _translate("RFreeze", "folder"))
        self.labelDevice.setText(_translate("RFreeze", "Device name:"))
        self.label_4.setText(_translate("RFreeze", "Folders not subjected to the freeze"))
        self.btnAddFolder.setText(_translate("RFreeze", "Add folder"))
        self.btnRmFolder.setText(_translate("RFreeze", "Remove folder"))
        self.busyBar.setFormat(_translate("RFreeze", "Working..."))
        self.busyLabel.setText(_translate("RFreeze", "Working..."))

