# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rfreeze.ui'
#
# Created: Wed Feb 18 04:42:38 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RFreeze(object):
    def setupUi(self, RFreeze):
        RFreeze.setObjectName("RFreeze")
        RFreeze.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RFreeze.sizePolicy().hasHeightForWidth())
        RFreeze.setSizePolicy(sizePolicy)
        RFreeze.setMinimumSize(QtCore.QSize(100, 0))
        RFreeze.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(RFreeze)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(RFreeze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.comboStorage = QtWidgets.QComboBox(RFreeze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboStorage.sizePolicy().hasHeightForWidth())
        self.comboStorage.setSizePolicy(sizePolicy)
        self.comboStorage.setObjectName("comboStorage")
        self.comboStorage.addItem("")
        self.comboStorage.addItem("")
        self.comboStorage.addItem("")
        self.horizontalLayout_6.addWidget(self.comboStorage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelDevice = QtWidgets.QLabel(RFreeze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDevice.sizePolicy().hasHeightForWidth())
        self.labelDevice.setSizePolicy(sizePolicy)
        self.labelDevice.setMinimumSize(QtCore.QSize(0, 0))
        self.labelDevice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDevice.setObjectName("labelDevice")
        self.horizontalLayout_5.addWidget(self.labelDevice)
        self.lineDevName = QtWidgets.QLineEdit(RFreeze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineDevName.sizePolicy().hasHeightForWidth())
        self.lineDevName.setSizePolicy(sizePolicy)
        self.lineDevName.setObjectName("lineDevName")
        self.horizontalLayout_5.addWidget(self.lineDevName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(RFreeze)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.folderList = QtWidgets.QListWidget(RFreeze)
        self.folderList.setObjectName("folderList")
        self.horizontalLayout_4.addWidget(self.folderList)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnEnable = QtWidgets.QPushButton(RFreeze)
        self.btnEnable.setObjectName("btnEnable")
        self.verticalLayout_3.addWidget(self.btnEnable)
        self.btnExit = QtWidgets.QPushButton(RFreeze)
        self.btnExit.setObjectName("btnExit")
        self.verticalLayout_3.addWidget(self.btnExit)
        self.btnAddFolder = QtWidgets.QCommandLinkButton(RFreeze)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/green-plus-th.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddFolder.setIcon(icon)
        self.btnAddFolder.setObjectName("btnAddFolder")
        self.verticalLayout_3.addWidget(self.btnAddFolder)
        self.btnRmFolder = QtWidgets.QCommandLinkButton(RFreeze)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/red-minus-th.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRmFolder.setIcon(icon1)
        self.btnRmFolder.setObjectName("btnRmFolder")
        self.verticalLayout_3.addWidget(self.btnRmFolder)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(RFreeze)
        QtCore.QMetaObject.connectSlotsByName(RFreeze)

    def retranslateUi(self, RFreeze):
        _translate = QtCore.QCoreApplication.translate
        RFreeze.setWindowTitle(_translate("RFreeze", "ROSA Freeze"))
        self.label.setText(_translate("RFreeze", "Storage type to store new file versions:"))
        self.comboStorage.setItemText(0, _translate("RFreeze", "tmpfs"))
        self.comboStorage.setItemText(1, _translate("RFreeze", "device"))
        self.comboStorage.setItemText(2, _translate("RFreeze", "folder"))
        self.labelDevice.setText(_translate("RFreeze", "Device name:"))
        self.label_2.setText(_translate("RFreeze", "Folders to skip:"))
        self.btnEnable.setText(_translate("RFreeze", "Enable"))
        self.btnExit.setText(_translate("RFreeze", "Exit"))
        self.btnAddFolder.setText(_translate("RFreeze", "Add folder"))
        self.btnRmFolder.setText(_translate("RFreeze", "Remove folder"))

